name: eqgat
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - pyg
dependencies:
  - python=3.9.0
  - pip
  - notebook
  - matplotlib
  - rdkit=2021.09.4
  - pytorch::pytorch=1.11.0
  - pyg::pyg==2.0.4
  - conda-forge::pytorch-lightning=1.7.4
  - pip:
    - biopandas==0.4.1
    - e3nn==0.5.0
    - atom3d==0.2.6